import { Migration } from '@mikro-orm/migrations'

/**
 * No-op migration.
 *
 * This migration was originally generated by `db:generate` against a local
 * database that contained tables from other modules (customers, fms, ksef,
 * sales). It duplicated the table creation already handled by
 * Migration20260409000002 and included dozens of unrelated ALTER TABLE
 * statements. It has been stripped to a no-op to keep the migration log
 * consistent for databases that already recorded it.
 */
export class Migration20260411151221 extends Migration {
  override async up(): Promise<void> {
    // Intentionally empty — table creation is handled by Migration20260409000002
  }

  override async down(): Promise<void> {
    // Intentionally empty
  }
}

export default Migration20260411151221
