import { Migration } from '@mikro-orm/migrations';

export class Migration20260209231805 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table "fms_projects" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_number" text not null, "client_id" uuid null, "rfq_id" uuid null, "offer_id" uuid null, "shipment_id" uuid null, "workflow_instance_id" uuid null, "current_step" text null, "workflow_context" jsonb null, "shipment_type" text not null, "direction" text not null, "cargo_type" text not null, "incoterm" text null, "transport_modes" jsonb null, "origin_location_id" uuid null, "destination_location_id" uuid null, "place_of_loading_id" uuid null, "place_of_discharge_id" uuid null, "origin_address" text null, "destination_address" text null, "project_date" timestamptz not null, "requested_pickup_date" timestamptz null, "requested_delivery_date" timestamptz null, "etd" timestamptz null, "eta" timestamptz null, "atd" timestamptz null, "ata" timestamptz null, "cargo_ready_date" timestamptz null, "vgm_cutoff_date" timestamptz null, "doc_cutoff_date" timestamptz null, "gate_in_date" timestamptz null, "gate_close_date" timestamptz null, "carrier_id" uuid null, "client_reference" text null, "internal_reference" text null, "commodity_description" text null, "hs_code" text null, "container_count" int null, "transport_unit_count" int null, "total_gross_weight" numeric(18,4) null, "total_volume" numeric(18,4) null, "weight_unit" text null, "volume_unit" text null, "currency_code" text not null default 'USD', "estimated_cost" numeric(18,4) null, "requires_insurance" boolean not null default false, "requires_customs_brokerage" boolean not null default false, "is_hazardous" boolean not null default false, "hazmat_details" text null, "special_instructions" text null, "internal_notes" text null, "container_mode" text null, "service_level" text null, "bl_number" text null, "bl_type" text null, "release_type" text null, "notify_party_id" uuid null, "controlling_agent_id" uuid null, "controlling_customer_id" uuid null, "sending_agent_id" uuid null, "receiving_agent_id" uuid null, "agents_reference" text null, "booking_number" text null, "operator_id" uuid null, "operator_name" text null, "sales_person_id" uuid null, "sales_person_name" text null, "shipper_id" uuid null, "consignee_id" uuid null, "goods_value" numeric(18,2) null, "goods_value_currency" text null, "insurance_value" numeric(18,2) null, "insurance_value_currency" text null, "is_domestic" boolean not null default false, "additional_terms" text null, "creditor_id" uuid null, "payment_terms" text null, "invoicing_status" text null, "ct_status" text null, "e_freight_status" text null, "charges_apply" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_projects_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_projects_client_idx" on "fms_projects" ("client_id", "organization_id", "tenant_id");`);
    this.addSql(`create index "fms_projects_status_idx" on "fms_projects" ("organization_id", "tenant_id", "current_step");`);
    this.addSql(`create index "fms_projects_workflow_idx" on "fms_projects" ("workflow_instance_id");`);
    this.addSql(`create index "fms_projects_org_tenant_idx" on "fms_projects" ("organization_id", "tenant_id");`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_number_unique" unique ("organization_id", "project_number");`);

    this.addSql(`create table "fms_project_notes" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "body" text not null, "author_user_id" uuid null, "author_name" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_project_notes_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_project_notes_project_idx" on "fms_project_notes" ("project_id");`);
    this.addSql(`create index "fms_project_notes_org_tenant_idx" on "fms_project_notes" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_project_lines" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "line_number" int not null default 0, "source_offer_line_id" uuid null, "source_type" text not null default 'manual', "product_id" uuid null, "price_id" uuid null, "product_name" text not null, "charge_code" text null, "container_size" text null, "charge_category" text null, "charge_unit" text null, "container_type" text null, "quantity" numeric(18,4) not null default '1', "currency_code" text not null default 'USD', "sold_unit_price" numeric(18,4) not null default '0', "sold_amount" numeric(18,4) not null default '0', "actual_unit_cost" numeric(18,4) null, "actual_cost" numeric(18,4) null, "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_project_lines_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_project_lines_project_idx" on "fms_project_lines" ("project_id");`);
    this.addSql(`create index "fms_project_lines_org_tenant_idx" on "fms_project_lines" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_project_legs" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "leg_sequence" int not null, "transport_mode" text not null, "origin_location_id" uuid null, "destination_location_id" uuid null, "origin_address" text null, "destination_address" text null, "carrier_id" uuid null, "carrier_name" text null, "vessel_name" text null, "voyage_number" text null, "flight_number" text null, "estimated_departure" timestamptz null, "estimated_arrival" timestamptz null, "actual_departure" timestamptz null, "actual_arrival" timestamptz null, "estimated_cost" numeric(18,4) null, "actual_cost" numeric(18,4) null, "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_project_legs_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_project_legs_project_idx" on "fms_project_legs" ("project_id", "leg_sequence");`);
    this.addSql(`create index "fms_project_legs_org_tenant_idx" on "fms_project_legs" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_project_invoices" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "document_id" uuid not null, "invoice_number" text null, "seller_name" text null, "seller_nip" text null, "seller_details" jsonb null, "buyer_name" text null, "buyer_nip" text null, "buyer_details" jsonb null, "net_amount" numeric(18,4) null, "vat_amount" numeric(18,4) null, "gross_amount" numeric(18,4) null, "currency_code" text not null default 'PLN', "invoice_date" timestamptz null, "payment_due_date" timestamptz null, "service_date" timestamptz null, "payment_method" text null, "line_items" jsonb null, "confidence" text not null default 'REVIEW', "extraction_strategies" jsonb null, "raw_extraction_data" jsonb null, "status" text not null default 'pending_review', "reviewed_by" uuid null, "reviewed_at" timestamptz null, "review_notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_project_invoices_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_project_invoices_status_idx" on "fms_project_invoices" ("status");`);
    this.addSql(`create index "fms_project_invoices_document_idx" on "fms_project_invoices" ("document_id");`);
    this.addSql(`create index "fms_project_invoices_project_idx" on "fms_project_invoices" ("project_id");`);
    this.addSql(`create index "fms_project_invoices_org_tenant_idx" on "fms_project_invoices" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_project_cargo" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "cargo_sequence" int null, "commodity_description" text not null, "hs_code" text null, "package_type" text not null, "package_count" int not null, "marks_and_numbers" text null, "length" numeric(18,4) null, "width" numeric(18,4) null, "height" numeric(18,4) null, "dimension_unit" text null, "gross_weight" numeric(18,4) not null, "net_weight" numeric(18,4) null, "weight_unit" text not null, "volume" numeric(18,4) null, "volume_unit" text null, "is_hazardous" boolean not null default false, "hazmat_class" text null, "un_number" text null, "is_stackable" boolean not null default true, "requires_refrigeration" boolean not null default false, "temperature_min" numeric(18,4) null, "temperature_max" numeric(18,4) null, "temperature_unit" text null, "declared_value" numeric(18,4) null, "declared_value_currency" text null, "status" text not null default 'not_ready', "notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_project_cargo_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_project_cargo_project_idx" on "fms_project_cargo" ("project_id");`);
    this.addSql(`create index "fms_project_cargo_org_tenant_idx" on "fms_project_cargo" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_air_units" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "delivery_status" text not null default 'awaiting', "is_loose" boolean not null default true, "is_stackable" boolean not null default true, "is_dgr" boolean not null default false, "dgr_un_number" text null, "dgr_class" text null, "pieces" int null, "gross_weight" numeric(18,4) null, "chargeable_weight" numeric(18,4) null, "volume" numeric(18,4) null, "loading_meters" numeric(18,4) null, "commodity" text null, "description" text null, "target_rate" numeric(18,4) null, "unit_type" text null, "unit_number" text null, "origin_type" text not null default 'airport', "origin_airport" text null, "destination_airport" text null, "shipment_ready_date" timestamptz null, "required_at_destination" timestamptz null, "etd" timestamptz null, "eta" timestamptz null, "atd" timestamptz null, "ata" timestamptz null, "mawb_number" text null, "hawb_number" text null, "booking_number" text null, "flight_number" text null, "carrier_code" text null, "aircraft_type" text null, "notes" text null, "customs_clearance_status" text null, "customs_clearance_location" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_air_units_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_air_units_mawb_idx" on "fms_air_units" ("mawb_number");`);
    this.addSql(`create index "fms_air_units_project_idx" on "fms_air_units" ("project_id");`);
    this.addSql(`create index "fms_air_units_org_tenant_idx" on "fms_air_units" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_road_units" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "vehicle_type" text not null, "truck_number" text null, "trailer_number" text null, "driver_name" text null, "driver_phone" text null, "cmr_number" text null, "booking_number" text null, "carrier_name" text null, "carrier_contact" text null, "origin_address" text null, "destination_address" text null, "pickup_date" timestamptz null, "delivery_date" timestamptz null, "actual_pickup" timestamptz null, "actual_delivery" timestamptz null, "pieces" int null, "gross_weight" numeric(18,4) null, "pallet_spaces" int null, "loading_meters" numeric(18,4) null, "status" text not null default 'not_ready', "is_hazardous" boolean not null default false, "notes" text null, "unloading_notes" text null, "weighing_status" text null, "rate" numeric(18,4) null, "rate_currency" text null default 'PLN', "customs_status" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_road_units_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_road_units_cmr_idx" on "fms_road_units" ("cmr_number");`);
    this.addSql(`create index "fms_road_units_project_idx" on "fms_road_units" ("project_id");`);
    this.addSql(`create index "fms_road_units_org_tenant_idx" on "fms_road_units" ("organization_id", "tenant_id");`);

    this.addSql(`create table "fms_sea_containers" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "project_id" uuid not null, "container_type" text not null, "container_number" text null, "seal_number" text null, "ownership_type" text not null default 'coc', "booking_number" text null, "bl_number" text null, "vessel_name" text null, "vessel_imo" text null, "voyage_number" text null, "origin_port" text null, "destination_port" text null, "etd" timestamptz null, "eta" timestamptz null, "atd" timestamptz null, "ata" timestamptz null, "status" text not null default 'not_ready', "is_hazardous" boolean not null default false, "notes" text null, "vgm_status" text null, "vgm_weight" numeric(12,3) null, "vgm_cutoff_date" timestamptz null, "customs_clearance_status" text null, "customs_clearance_location" text null, "pin_code" text null, "delivery_time" text null, "drop_off_location" text null, "cut_off_date" timestamptz null, "packs_count" int null, "pack_type" text null, "inners_count" int null, "inner_type" text null, "loading_meters" numeric(12,3) null, "chargeable_weight" numeric(12,3) null, "wv_ratio" numeric(8,4) null, "marks_and_numbers" text null, "hs_code" text null, "on_board_status" text null, "on_board_date" timestamptz null, "bl_issue_date" timestamptz null, "originals_count" int null, "express_bills_count" int null, "carrier_scac" text null, "imo_number" text null, "cto_receival_date" timestamptz null, "cto_cut_off_date" timestamptz null, "docs_due_date" timestamptz null, "co2_emissions" numeric(12,3) null, "pickup_required_from" timestamptz null, "pickup_required_by" timestamptz null, "estimated_pickup" timestamptz null, "actual_pickup" timestamptz null, "pickup_location_id" uuid null, "pickup_notes" text null, "delivery_required_by" timestamptz null, "estimated_delivery" timestamptz null, "actual_delivery" timestamptz null, "delivery_location_id" uuid null, "delivery_notes" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "fms_sea_containers_pkey" primary key ("id"));`);
    this.addSql(`create index "fms_sea_containers_number_idx" on "fms_sea_containers" ("container_number");`);
    this.addSql(`create index "fms_sea_containers_project_idx" on "fms_sea_containers" ("project_id");`);
    this.addSql(`create index "fms_sea_containers_org_tenant_idx" on "fms_sea_containers" ("organization_id", "tenant_id");`);

    this.addSql(`alter table "fms_projects" add constraint "fms_projects_client_id_foreign" foreign key ("client_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_rfq_id_foreign" foreign key ("rfq_id") references "fms_rfqs" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_offer_id_foreign" foreign key ("offer_id") references "fms_offers" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_origin_location_id_foreign" foreign key ("origin_location_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_destination_location_id_foreign" foreign key ("destination_location_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_place_of_loading_id_foreign" foreign key ("place_of_loading_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_place_of_discharge_id_foreign" foreign key ("place_of_discharge_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_carrier_id_foreign" foreign key ("carrier_id") references "fms_carriers" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_notify_party_id_foreign" foreign key ("notify_party_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_controlling_agent_id_foreign" foreign key ("controlling_agent_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_controlling_customer_id_foreign" foreign key ("controlling_customer_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_sending_agent_id_foreign" foreign key ("sending_agent_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_receiving_agent_id_foreign" foreign key ("receiving_agent_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_shipper_id_foreign" foreign key ("shipper_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_consignee_id_foreign" foreign key ("consignee_id") references "contractors" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_projects" add constraint "fms_projects_creditor_id_foreign" foreign key ("creditor_id") references "contractors" ("id") on update cascade on delete set null;`);

    this.addSql(`alter table "fms_project_notes" add constraint "fms_project_notes_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_project_lines" add constraint "fms_project_lines_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_project_legs" add constraint "fms_project_legs_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);
    this.addSql(`alter table "fms_project_legs" add constraint "fms_project_legs_origin_location_id_foreign" foreign key ("origin_location_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_project_legs" add constraint "fms_project_legs_destination_location_id_foreign" foreign key ("destination_location_id") references "fms_locations" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fms_project_legs" add constraint "fms_project_legs_carrier_id_foreign" foreign key ("carrier_id") references "contractors" ("id") on update cascade on delete set null;`);

    this.addSql(`alter table "fms_project_invoices" add constraint "fms_project_invoices_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_project_cargo" add constraint "fms_project_cargo_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_air_units" add constraint "fms_air_units_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_road_units" add constraint "fms_road_units_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);

    this.addSql(`alter table "fms_sea_containers" add constraint "fms_sea_containers_project_id_foreign" foreign key ("project_id") references "fms_projects" ("id") on update cascade;`);
  }

}
