import type { Template } from '@pdfme/common'

const BLACK = '#111111'
const GRAY = '#666666'
const LIGHT = '#e5e5e5'

export const DEFAULT_INVOICE_TEMPLATE = {
  basePdf: { width: 210, height: 297, padding: [10, 10, 10, 10] },
  schemas: [
    [
      // ---- HEADER ----
      {
        name: 'invoiceTitle',
        type: 'text',
        content: '{invoiceTitle}',
        position: { x: 10, y: 10 },
        width: 80,
        height: 10,
        fontSize: 18,
        fontWeight: 'bold',
        fontColor: BLACK,
        readOnly: true,
      },
      {
        name: 'invoiceNumberLabel',
        type: 'text',
        content: '{invoiceNumber}',
        position: { x: 10, y: 20 },
        width: 80,
        height: 7,
        fontSize: 10,
        fontColor: GRAY,
        readOnly: true,
      },

      // Dates (right column)
      {
        name: 'invoiceDateRow',
        type: 'text',
        content: '{invoiceDateLabel}: {invoiceDate}',
        position: { x: 120, y: 10 },
        width: 80,
        height: 6,
        fontSize: 9,
        fontColor: GRAY,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'serviceDateRow',
        type: 'text',
        content: '{serviceDateLabel}: {serviceDate}',
        position: { x: 120, y: 16 },
        width: 80,
        height: 6,
        fontSize: 9,
        fontColor: GRAY,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'dueDateRow',
        type: 'text',
        content: '{dueDateLabel}: {dueDate}',
        position: { x: 120, y: 22 },
        width: 80,
        height: 6,
        fontSize: 9,
        fontColor: GRAY,
        alignment: 'right',
        readOnly: true,
      },

      // Header separator
      {
        name: 'headerLine',
        type: 'line',
        position: { x: 10, y: 30 },
        width: 190,
        height: 0.2,
        color: LIGHT,
        readOnly: true,
      },

      // ---- SELLER / BUYER ----
      {
        name: 'sellerLabel',
        type: 'text',
        content: '{sellerLabel}',
        position: { x: 10, y: 34 },
        width: 90,
        height: 5,
        fontSize: 7,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'sellerName',
        type: 'text',
        content: '{sellerName}',
        position: { x: 10, y: 39 },
        width: 90,
        height: 7,
        fontSize: 10,
        fontWeight: 'bold',
        fontColor: BLACK,
        readOnly: true,
      },
      {
        name: 'sellerNipRow',
        type: 'text',
        content: '{sellerNipLabel}: {sellerNip}',
        position: { x: 10, y: 46 },
        width: 90,
        height: 5,
        fontSize: 8,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'sellerAddress',
        type: 'text',
        content: '{sellerAddress}',
        position: { x: 10, y: 51 },
        width: 90,
        height: 8,
        fontSize: 8,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'sellerBankRow',
        type: 'text',
        content: '{sellerBankAccountLabel}: {sellerBankAccount}',
        position: { x: 10, y: 59 },
        width: 90,
        height: 5,
        fontSize: 7,
        fontColor: GRAY,
        readOnly: true,
      },

      {
        name: 'buyerLabel',
        type: 'text',
        content: '{buyerLabel}',
        position: { x: 110, y: 34 },
        width: 90,
        height: 5,
        fontSize: 7,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'buyerName',
        type: 'text',
        content: '{buyerName}',
        position: { x: 110, y: 39 },
        width: 90,
        height: 7,
        fontSize: 10,
        fontWeight: 'bold',
        fontColor: BLACK,
        readOnly: true,
      },
      {
        name: 'buyerNipRow',
        type: 'text',
        content: '{buyerNipLabel}: {buyerNip}',
        position: { x: 110, y: 46 },
        width: 90,
        height: 5,
        fontSize: 8,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'buyerAddress',
        type: 'text',
        content: '{buyerAddress}',
        position: { x: 110, y: 51 },
        width: 90,
        height: 8,
        fontSize: 8,
        fontColor: GRAY,
        readOnly: true,
      },

      // ---- LINE ITEMS TABLE ----
      {
        name: 'lineItemsTable',
        type: 'table',
        position: { x: 10, y: 70 },
        width: 190,
        height: 150,
        showHead: true,
        head: ['Lp.', 'Opis', 'J.m.', 'Ilosc', 'Cena netto', 'Stawka VAT', 'Netto', 'VAT', 'Brutto'],
        headWidthPercentages: [5, 28, 6, 6, 12, 9, 12, 9, 13],
        tableStyles: { borderWidth: 0 },
        headStyles: {
          fontName: 'Roboto',
          fontSize: 7,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: GRAY,
          borderColor: '',
          backgroundColor: '',
          borderWidth: { top: 0, right: 0, bottom: 0.3, left: 0 },
          padding: { top: 3, right: 2, bottom: 3, left: 2 },
        },
        bodyStyles: {
          fontName: 'Roboto',
          fontSize: 8,
          characterSpacing: 0,
          alignment: 'right',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: BLACK,
          borderColor: LIGHT,
          backgroundColor: '',
          alternateBackgroundColor: '',
          borderWidth: { top: 0, right: 0, bottom: 0.2, left: 0 },
          padding: { top: 3, right: 2, bottom: 3, left: 2 },
        },
        columnStyles: {
          0: { alignment: 'center' },
          1: { alignment: 'left' },
          2: { alignment: 'center' },
          3: { alignment: 'center' },
        },
      },

      // ---- TOTALS ----
      {
        name: 'netTotalRow',
        type: 'text',
        content: '{netTotalLabel}: {netTotal}',
        position: { x: 110, y: 224 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: GRAY,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'vatTotalRow',
        type: 'text',
        content: '{vatTotalLabel}: {vatTotal}',
        position: { x: 110, y: 230 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: GRAY,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'grossTotalRow',
        type: 'text',
        content: '{grossTotalLabel}: {grossTotal}',
        position: { x: 110, y: 237 },
        width: 90,
        height: 8,
        fontSize: 12,
        fontWeight: 'bold',
        fontColor: BLACK,
        alignment: 'right',
        readOnly: true,
      },

      // ---- PAYMENT ----
      {
        name: 'paymentRow',
        type: 'text',
        content: '{paymentMethodLabel}: {paymentMethod}',
        position: { x: 10, y: 224 },
        width: 90,
        height: 5,
        fontSize: 8,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'notes',
        type: 'text',
        content: '{notes}',
        position: { x: 10, y: 230 },
        width: 90,
        height: 15,
        fontSize: 7,
        fontColor: GRAY,
        readOnly: true,
      },

      // ---- FOOTER: KSeF & QR CODE ----
      {
        name: 'footerLine',
        type: 'line',
        position: { x: 10, y: 255 },
        width: 190,
        height: 0.2,
        color: LIGHT,
        readOnly: true,
      },
      {
        name: 'ksefLabel',
        type: 'text',
        content: '{ksefLabel}',
        position: { x: 10, y: 258 },
        width: 30,
        height: 5,
        fontSize: 7,
        fontColor: GRAY,
        readOnly: true,
      },
      {
        name: 'ksefNumber',
        type: 'text',
        content: '{ksefNumber}',
        position: { x: 10, y: 263 },
        width: 150,
        height: 6,
        fontSize: 7,
        fontColor: BLACK,
        readOnly: true,
      },
      {
        name: 'ksefQrCode',
        type: 'qrcode',
        content: '{ksefVerificationUrl}',
        position: { x: 172, y: 257 },
        width: 28,
        height: 28,
        readOnly: true,
      },
    ],
  ],
} as Template
