import type { Template } from '@pdfme/common'

const PRIMARY = '#1a365d'
const BORDER = '#cbd5e1'
const MUTED = '#64748b'

// Template uses extended pdfme schema properties (table styles, column styles)
// that aren't fully captured by the base Schema type, so we use a cast.
export const DEFAULT_INVOICE_TEMPLATE = {
  basePdf: { width: 210, height: 297, padding: [10, 10, 10, 10] },
  schemas: [
    [
      // ---- HEADER ----
      {
        name: 'invoiceTitle',
        type: 'text',
        content: '{invoiceTitle}',
        position: { x: 10, y: 10 },
        width: 90,
        height: 12,
        fontSize: 22,
        fontWeight: 'bold',
        fontColor: PRIMARY,
        readOnly: true,
      },
      {
        name: 'invoiceNumberLabel',
        type: 'text',
        content: '{invoiceNumberLabel}: {invoiceNumber}',
        position: { x: 110, y: 10 },
        width: 90,
        height: 8,
        fontSize: 11,
        fontColor: PRIMARY,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'invoiceDateRow',
        type: 'text',
        content: '{invoiceDateLabel}: {invoiceDate}',
        position: { x: 110, y: 19 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: MUTED,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'serviceDateRow',
        type: 'text',
        content: '{serviceDateLabel}: {serviceDate}',
        position: { x: 110, y: 25 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: MUTED,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'dueDateRow',
        type: 'text',
        content: '{dueDateLabel}: {dueDate}',
        position: { x: 110, y: 31 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: MUTED,
        alignment: 'right',
        readOnly: true,
      },
      // Header separator
      {
        name: 'headerLine',
        type: 'line',
        position: { x: 10, y: 39 },
        width: 190,
        height: 0.3,
        color: BORDER,
        readOnly: true,
      },

      // ---- SELLER / BUYER ----
      {
        name: 'sellerLabel',
        type: 'text',
        content: '{sellerLabel}',
        position: { x: 10, y: 42 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontWeight: 'bold',
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'sellerName',
        type: 'text',
        content: '{sellerName}',
        position: { x: 10, y: 48 },
        width: 90,
        height: 8,
        fontSize: 11,
        fontWeight: 'bold',
        fontColor: PRIMARY,
        readOnly: true,
      },
      {
        name: 'sellerNipRow',
        type: 'text',
        content: '{sellerNipLabel}: {sellerNip}',
        position: { x: 10, y: 57 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'sellerAddress',
        type: 'text',
        content: '{sellerAddress}',
        position: { x: 10, y: 64 },
        width: 90,
        height: 10,
        fontSize: 9,
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'sellerBankRow',
        type: 'text',
        content: '{sellerBankAccountLabel}: {sellerBankAccount}',
        position: { x: 10, y: 75 },
        width: 90,
        height: 6,
        fontSize: 8,
        fontColor: MUTED,
        readOnly: true,
      },

      {
        name: 'buyerLabel',
        type: 'text',
        content: '{buyerLabel}',
        position: { x: 110, y: 42 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontWeight: 'bold',
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'buyerName',
        type: 'text',
        content: '{buyerName}',
        position: { x: 110, y: 48 },
        width: 90,
        height: 8,
        fontSize: 11,
        fontWeight: 'bold',
        fontColor: PRIMARY,
        readOnly: true,
      },
      {
        name: 'buyerNipRow',
        type: 'text',
        content: '{buyerNipLabel}: {buyerNip}',
        position: { x: 110, y: 57 },
        width: 90,
        height: 6,
        fontSize: 9,
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'buyerAddress',
        type: 'text',
        content: '{buyerAddress}',
        position: { x: 110, y: 64 },
        width: 90,
        height: 10,
        fontSize: 9,
        fontColor: MUTED,
        readOnly: true,
      },

      // Party separator
      {
        name: 'partyLine',
        type: 'line',
        position: { x: 10, y: 84 },
        width: 190,
        height: 0.3,
        color: BORDER,
        readOnly: true,
      },

      // ---- LINE ITEMS TABLE ----
      {
        name: 'lineItemsTable',
        type: 'table',
        position: { x: 10, y: 88 },
        width: 190,
        height: 150,
        showHead: true,
        head: ['Lp.', 'Opis', 'J.m.', 'Ilosc', 'Cena netto', 'Stawka VAT', 'Netto', 'VAT', 'Brutto'],
        headWidthPercentages: [5, 25, 6, 7, 12, 10, 12, 10, 13],
        tableStyles: { borderWidth: 0.3, borderColor: BORDER },
        headStyles: {
          fontName: 'Roboto',
          fontSize: 8,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#ffffff',
          borderColor: PRIMARY,
          backgroundColor: PRIMARY,
          borderWidth: { top: 0.3, right: 0.3, bottom: 0.3, left: 0.3 },
          padding: { top: 3, right: 2, bottom: 3, left: 2 },
        },
        bodyStyles: {
          fontName: 'Roboto',
          fontSize: 8,
          characterSpacing: 0,
          alignment: 'right',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#1e293b',
          borderColor: BORDER,
          backgroundColor: '',
          alternateBackgroundColor: '#f8fafc',
          borderWidth: { top: 0, right: 0.3, bottom: 0.3, left: 0.3 },
          padding: { top: 3, right: 2, bottom: 3, left: 2 },
        },
        columnStyles: {
          0: { alignment: 'center' },
          1: { alignment: 'left' },
          2: { alignment: 'center' },
          3: { alignment: 'center' },
        },
      },

      // ---- TOTALS ----
      {
        name: 'totalsLine',
        type: 'line',
        position: { x: 10, y: 232 },
        width: 190,
        height: 0.3,
        color: BORDER,
        readOnly: true,
      },
      {
        name: 'netTotalRow',
        type: 'text',
        content: '{netTotalLabel}: {netTotal}',
        position: { x: 110, y: 235 },
        width: 90,
        height: 6,
        fontSize: 10,
        fontColor: MUTED,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'vatTotalRow',
        type: 'text',
        content: '{vatTotalLabel}: {vatTotal}',
        position: { x: 110, y: 241 },
        width: 90,
        height: 6,
        fontSize: 10,
        fontColor: MUTED,
        alignment: 'right',
        readOnly: true,
      },
      {
        name: 'grossTotalRow',
        type: 'text',
        content: '{grossTotalLabel}: {grossTotal}',
        position: { x: 110, y: 247 },
        width: 90,
        height: 8,
        fontSize: 13,
        fontWeight: 'bold',
        fontColor: PRIMARY,
        alignment: 'right',
        readOnly: true,
      },

      // ---- PAYMENT & NOTES ----
      {
        name: 'paymentLine',
        type: 'line',
        position: { x: 10, y: 258 },
        width: 190,
        height: 0.3,
        color: BORDER,
        readOnly: true,
      },
      {
        name: 'paymentRow',
        type: 'text',
        content: '{paymentMethodLabel}: {paymentMethod}',
        position: { x: 10, y: 261 },
        width: 100,
        height: 5,
        fontSize: 9,
        fontColor: MUTED,
        readOnly: true,
      },
      {
        name: 'notes',
        type: 'text',
        content: '{notes}',
        position: { x: 10, y: 268 },
        width: 190,
        height: 20,
        fontSize: 8,
        fontColor: MUTED,
        readOnly: true,
      },
    ],
  ],
} as Template
